# Site settings
title: Pavel 1st Medicine
email: admin@p1m.org
url: https://p1m.org
description: "P1M is an Open Science collaboration from Saint Petersburg, Russia. With its primary focus in orthopedic spine surgery and evidence synthesis, it is now running a range of research projects in health care and beyond. Check GitHub for our portfolio. "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#487393'

# Footer settings
footer: P1M.ORG

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/drzhelnov
  - title: github
    url: https://github.com/p1m-ortho

# Build settings
markdown: kramdown
permalink: pretty
