# Site settings
title: Pick One Medicine
email: admin@p1m.org
url: https://p1m.org
description: "P1M aggregates cutting-edge medical research and makes health evidence accessible to everyone. Our mission is to empower people worldwide for informed health decisions."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#00688b'

# Footer settings
footer: P1M.ORG

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/drzhelnov
#  - title: github
#    url: https://github.com/p1m-ortho

# Build settings
markdown: kramdown
permalink: pretty
